---

plugins:
  - import

env:
  node: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

rules:
  no-console: 0
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
